#pragma once

// From glfw3.h
#define BBZ_KEY_SPACE              32
#define BBZ_KEY_APOSTROPHE         39
#define BBZ_KEY_COMMA              44
#define BBZ_KEY_MINUS              45
#define BBZ_KEY_PERIOD             46
#define BBZ_KEY_SLASH              47
#define BBZ_KEY_0                  48
#define BBZ_KEY_1                  49
#define BBZ_KEY_2                  50
#define BBZ_KEY_3                  51
#define BBZ_KEY_4                  52
#define BBZ_KEY_5                  53
#define BBZ_KEY_6                  54
#define BBZ_KEY_7                  55
#define BBZ_KEY_8                  56
#define BBZ_KEY_9                  57
#define BBZ_KEY_SEMICOLON          59
#define BBZ_KEY_EQUAL              61
#define BBZ_KEY_A                  65
#define BBZ_KEY_B                  66
#define BBZ_KEY_C                  67
#define BBZ_KEY_D                  68
#define BBZ_KEY_E                  69
#define BBZ_KEY_F                  70
#define BBZ_KEY_G                  71
#define BBZ_KEY_H                  72
#define BBZ_KEY_I                  73
#define BBZ_KEY_J                  74
#define BBZ_KEY_K                  75
#define BBZ_KEY_L                  76
#define BBZ_KEY_M                  77
#define BBZ_KEY_N                  78
#define BBZ_KEY_O                  79
#define BBZ_KEY_P                  80
#define BBZ_KEY_Q                  81
#define BBZ_KEY_R                  82
#define BBZ_KEY_S                  83
#define BBZ_KEY_T                  84
#define BBZ_KEY_U                  85
#define BBZ_KEY_V                  86
#define BBZ_KEY_W                  87
#define BBZ_KEY_X                  88
#define BBZ_KEY_Y                  89
#define BBZ_KEY_Z                  90
#define BBZ_KEY_LEFT_BRACKET       91
#define BBZ_KEY_BACKSLASH          92
#define BBZ_KEY_RIGHT_BRACKET      93
#define BBZ_KEY_GRAVE_ACCENT       96
#define BBZ_KEY_WORLD_1            161
#define BBZ_KEY_WORLD_2            162

/* Function keys */
#define BBZ_KEY_ESCAPE             256
#define BBZ_KEY_ENTER              257
#define BBZ_KEY_TAB                258
#define BBZ_KEY_BACKSPACE          259
#define BBZ_KEY_INSERT             260
#define BBZ_KEY_DELETE             261
#define BBZ_KEY_RIGHT              262
#define BBZ_KEY_LEFT               263
#define BBZ_KEY_DOWN               264
#define BBZ_KEY_UP                 265
#define BBZ_KEY_PAGE_UP            266
#define BBZ_KEY_PAGE_DOWN          267
#define BBZ_KEY_HOME               268
#define BBZ_KEY_END                269
#define BBZ_KEY_CAPS_LOCK          280
#define BBZ_KEY_SCROLL_LOCK        281
#define BBZ_KEY_NUM_LOCK           282
#define BBZ_KEY_PRINT_SCREEN       283
#define BBZ_KEY_PAUSE              284
#define BBZ_KEY_F1                 290
#define BBZ_KEY_F2                 291
#define BBZ_KEY_F3                 292
#define BBZ_KEY_F4                 293
#define BBZ_KEY_F5                 294
#define BBZ_KEY_F6                 295
#define BBZ_KEY_F7                 296
#define BBZ_KEY_F8                 297
#define BBZ_KEY_F9                 298
#define BBZ_KEY_F10                299
#define BBZ_KEY_F11                300
#define BBZ_KEY_F12                301
#define BBZ_KEY_F13                302
#define BBZ_KEY_F14                303
#define BBZ_KEY_F15                304
#define BBZ_KEY_F16                305
#define BBZ_KEY_F17                306
#define BBZ_KEY_F18                307
#define BBZ_KEY_F19                308
#define BBZ_KEY_F20                309
#define BBZ_KEY_F21                310
#define BBZ_KEY_F22                311
#define BBZ_KEY_F23                312
#define BBZ_KEY_F24                313
#define BBZ_KEY_F25                314
#define BBZ_KEY_KP_0               320
#define BBZ_KEY_KP_1               321
#define BBZ_KEY_KP_2               322
#define BBZ_KEY_KP_3               323
#define BBZ_KEY_KP_4               324
#define BBZ_KEY_KP_5               325
#define BBZ_KEY_KP_6               326
#define BBZ_KEY_KP_7               327
#define BBZ_KEY_KP_8               328
#define BBZ_KEY_KP_9               329
#define BBZ_KEY_KP_DECIMAL         330
#define BBZ_KEY_KP_DIVIDE          331
#define BBZ_KEY_KP_MULTIPLY        332
#define BBZ_KEY_KP_SUBTRACT        333
#define BBZ_KEY_KP_ADD             334
#define BBZ_KEY_KP_ENTER           335
#define BBZ_KEY_KP_EQUAL           336
#define BBZ_KEY_LEFT_SHIFT         340
#define BBZ_KEY_LEFT_CONTROL       341
#define BBZ_KEY_LEFT_ALT           342
#define BBZ_KEY_LEFT_SUPER         343
#define BBZ_KEY_RIGHT_SHIFT        344
#define BBZ_KEY_RIGHT_CONTROL      345
#define BBZ_KEY_RIGHT_ALT          346
#define BBZ_KEY_RIGHT_SUPER        347
#define BBZ_KEY_MENU               348
#define BBZ_MOUSE_BUTTON_1         0
#define BBZ_MOUSE_BUTTON_2         1
#define BBZ_MOUSE_BUTTON_3         2
#define BBZ_MOUSE_BUTTON_4         3
#define BBZ_MOUSE_BUTTON_5         4
#define BBZ_MOUSE_BUTTON_6         5
#define BBZ_MOUSE_BUTTON_7         6
#define BBZ_MOUSE_BUTTON_8         7
#define BBZ_MOUSE_BUTTON_LAST      BBZ_MOUSE_BUTTON_8
#define BBZ_MOUSE_BUTTON_LEFT      BBZ_MOUSE_BUTTON_1
#define BBZ_MOUSE_BUTTON_RIGHT     BBZ_MOUSE_BUTTON_2
#define BBZ_MOUSE_BUTTON_MIDDLE    BBZ_MOUSE_BUTTON_3